apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
  labels:
    app: iperf3-server
spec:
  nodeSelector:
    kubernetes.io/hostname: cni-perf-group-4-worker
  containers:
  - name: iperf3-server
    image: networkstatic/iperf3
    args: ["-s"]
    ports:
    - containerPort: 5201
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client
  labels:
    app: iperf3-client
spec:
  nodeSelector:
    kubernetes.io/hostname: cni-perf-group-4-worker2
  containers:
  - name: iperf3-client
    image: networkstatic/iperf3
    command: ["sleep", "infinity"]